name: myAutomatization

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  hello:
    runs-on: ubuntu-latest

    steps:
       - name: Hello Step
         run : echo "Hello From Git Hub Actions!"

       - name: Clone repository
         uses: actions/checkout@v3
       
       - name: List directories
         run : ls -la

       
         

  bye:
    runs-on: ubuntu-latest
    needs: [hello]

    steps:
      - name: Bye  step
        run : echo "Bye Bye!"
